import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://automationexercise.com/login');
  await page.getByText('New User Signup! Signup').click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('Joana');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('joanna@example.com');
  await page.getByRole('button', { name: 'Signup' }).click();
  await page.getByRole('radio', { name: 'Mrs.' }).check();
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('ice123');
  await page.locator('#days').selectOption('19');
  await page.locator('#months').selectOption('12');
  await page.locator('#years').selectOption('2003');
  await page.getByRole('textbox', { name: 'First name *' }).click();
  await page.getByRole('textbox', { name: 'First name *' }).fill('aefeaw');
  await page.getByRole('textbox', { name: 'Last name *' }).click();
  await page.getByRole('textbox', { name: 'Last name *' }).fill('dasf');
  await page.getByLabel('Country *').selectOption('Canada');
  await page.getByRole('textbox', { name: 'State *' }).click();
  await page.getByRole('textbox', { name: 'State *' }).fill('dasfad');
  await page.getByRole('textbox', { name: 'City * Zipcode *' }).click();
  await page.getByRole('textbox', { name: 'City * Zipcode *' }).fill('sdcsa');
  await page.locator('#zipcode').click();
  await page.locator('#zipcode').fill('s12324');
  await page.getByRole('textbox', { name: 'Mobile Number *' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number *' }).fill('+1233456781');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).fill('asd');
  await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).click();
  await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).fill('asda');
  await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).fill('asdaDF');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByText('You can now take advantage of').click();
  await page.getByText('Account Created!').click();
  await page.getByRole('link', { name: 'Continue' }).click();
  await page.locator('iframe[name="aswift_2"]').contentFrame().locator('iframe[name="ad_iframe"]').contentFrame().getByRole('button', { name: 'Close ad' }).click();
  await page.getByText('Logged in as Joana').click();
  await page.getByText('Logged in as Joana').click();
  await page.getByText('Logged in as Joana').click();
  await page.getByRole('link', { name: ' View Product' }).nth(3).click();
  await page.locator('#quantity').click();
  await page.locator('#quantity').fill('2');
  await page.getByText('Rs. 1500 Quantity: Add to cart').click();
  await page.getByRole('button', { name: ' Add to cart' }).click();
  await page.getByRole('heading', { name: 'Added!' }).click();
  await page.getByRole('link', { name: 'View Cart' }).click();
  await page.getByRole('button', { name: '2' }).click();
  await page.getByText('Rs. 1500').click();
  await page.getByText('Rs. 3000').click();
  await page.getByRole('link', { name: 'Stylish Dress' }).click();
  await page.getByRole('link', { name: ' Cart' }).click();
  await page.getByText('Proceed To Checkout').click();
  await page.locator('textarea[name="message"]').click();
  await page.locator('textarea[name="message"]').fill('awefarwf');
  await page.getByRole('link', { name: 'Place Order' }).click();
  await page.locator('input[name="name_on_card"]').click();
  await page.locator('input[name="name_on_card"]').fill('dsa');
  await page.locator('input[name="card_number"]').click();
  await page.locator('input[name="card_number"]').fill('231243431');
  await page.getByRole('textbox', { name: 'ex.' }).click();
  await page.getByRole('textbox', { name: 'ex.' }).click();
  await page.getByRole('textbox', { name: 'ex.' }).fill('311');
  await page.locator('div').filter({ hasText: 'Expiration' }).nth(5).click();
  await page.getByRole('textbox', { name: 'MM' }).click();
  await page.getByRole('textbox', { name: 'MM' }).fill('12');
  await page.getByRole('textbox', { name: 'YYYY' }).click();
  await page.getByRole('textbox', { name: 'YYYY' }).fill('2026');
  await page.getByRole('button', { name: 'Pay and Confirm Order' }).click();
  await page.getByText('Order Placed! Congratulations').click();
  await page.getByText('Order Placed!').click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download Invoice' }).click();
  const download = await downloadPromise;
  await page.getByRole('link', { name: 'Continue' }).click();
});